# Docker Compose file


version: '3.8'

services:
  db_dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ninoDB_dev
    ports:
      - "3307:3306"
    volumes:
      - db-dev-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db_dev
    env_file:
      - ./.env
    networks:
      - nino-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - nino-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
      - REACT_APP_AUTH0_DOMAIN=dev-o1xeu62jffl0qj1r.us.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=fAxuXOSMwuxOl8Z2vhGtd5fLV94Y5Cep
      - REACT_APP_API_AUDIENCE=https://merchandisemanagement.nino.com


volumes:
  db-dev-data:

networks:
  nino-network:
