# Docker Compose file

version: '3.8'

services:
  db_dev:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ninoDB_dev
    ports:
      - "3307:3306"
    volumes:
      - db-dev-data:/var/lib/mysql

  db_prod:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ninoDB_prod
    ports:
      - "3308:3306"
    volumes:
      - db-prod-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db_dev
    env_file:
      - ./.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-dev-data:
  db-prod-data:
