"""Altered Inventory and CreditCardInfo

Revision ID: 2b00c2335f6b
Revises: 54cc7a40e772
Create Date: 2024-02-19 22:09:02.129447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b00c2335f6b'
down_revision = '54cc7a40e772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('credit_card_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('credit_card_info_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('sales_summary_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('count_in',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('count_out',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('item_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('sales_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('soft_owed_casino', sa.Float(), nullable=False))
        batch_op.alter_column('total_gross',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('soft_gross',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('hard_gross',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('hard_owed',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('house_due',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('artist_revenue',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('soft_owed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soft_owed', mysql.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('artist_revenue',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('house_due',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('hard_owed',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('hard_gross',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('soft_gross',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('total_gross',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('soft_owed_casino')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('item_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('count_out',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('count_in',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('credit_card_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_summary_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('credit_card_info_ibfk_1', 'sales_summary', ['sales_summary_id'], ['summary_id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('configuration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
