"""empty message

Revision ID: 5c9d8446de55
Revises: 2b00c2335f6b
Create Date: 2024-02-20 19:45:49.373314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c9d8446de55'
down_revision = '2b00c2335f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soft_owed', sa.Float(), nullable=False))
        batch_op.drop_column('soft_owed_casino')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('soft_owed_casino', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('soft_owed')

    # ### end Alembic commands ###
